import moment from 'moment';

const date: Array<object> = [
  {
    id: 1,
    date: moment(new Date())
      .add(-3, 'days')
      .format('D'),
    day: moment(new Date())
      .add(-3, 'days')
      .format('ddd'),
    selectDate: moment(new Date())
      .add(-3, 'days')
      .format('YYYY-MM-DD'),
    disabled: true,
    active: false,
  },
  {
    id: 2,
    date: moment(new Date())
      .add(-2, 'days')
      .format('D'),
    day: moment(new Date())
      .add(-2, 'days')
      .format('ddd'),
    selectDate: moment(new Date())
      .add(-2, 'days')
      .format('YYYY-MM-DD'),
    disabled: true,
    active: false,
  },
  {
    id: 3,
    date: moment(new Date())
      .add(-1, 'days')
      .format('D'),
    day: moment(new Date())
      .add(-1, 'days')
      .format('ddd'),
    selectDate: moment(new Date())
      .add(-1, 'days')
      .format('YYYY-MM-DD'),
    disabled: true,
    active: false,
  },
  {
    id: 4,
    date: moment(new Date()).format('D'),
    day: moment(new Date())
      .add(0, 'days')
      .format('ddd'),
    selectDate: moment(new Date()).format('YYYY-MM-DD'),
    disabled: false,
    active: true,
  },
  {
    id: 5,
    date: moment(new Date())
      .add(1, 'days')
      .format('D'),
    day: moment(new Date())
      .add(1, 'days')
      .format('ddd'),
    selectDate: moment(new Date())
      .add(1, 'days')
      .format('YYYY-MM-DD'),
    disabled: false,
    active: false,
  },
  {
    id: 6,
    date: moment(new Date())
      .add(2, 'days')
      .format('D'),
    day: moment(new Date())
      .add(2, 'days')
      .format('ddd'),
    selectDate: moment(new Date())
      .add(2, 'days')
      .format('YYYY-MM-DD'),
    disabled: false,
    active: false,
  },
  {
    id: 7,
    date: moment(new Date())
      .add(3, 'days')
      .format('D'),
    day: moment(new Date())
      .add(3, 'days')
      .format('ddd'),
    selectDate: moment(new Date())
      .add(3, 'days')
      .format('YYYY-MM-DD'),
    disabled: false,
    active: false,
  },
];

const dataFlight: Array<object> = [
  {
    arrival_date: '2020-01-16 07:55:00',
    arrival_time: '07:55',
    departure_date: '2020-01-16 04:55:00',
    departure_time: '04:55',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 07:55',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 04:55',
        duration_hour: '2',
        duration_minute: '0',
        duration_time: 120,
        flight_number: 'QG-680',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '07:55',
        simple_departure_time: '04:55',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '2 j ',
    flight_number: 'QG-680',
    full_via: 'CGK-DPS(04:55-07:55)',
    name: 'Citilink',
    price_adult: 1216000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      '981f1b96a950b5a65cffbf1dbc134ac00ad3e6eb377d169f08bf12744f10cdac',
    stop: 'Langsung',
  },
  {
    arrival_date: '2020-01-16 10:35:00',
    arrival_time: '10:35',
    departure_date: '2020-01-16 07:35:00',
    departure_time: '07:35',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 10:35',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 07:35',
        duration_hour: '2',
        duration_minute: '0',
        duration_time: 120,
        flight_number: 'QG-682',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '10:35',
        simple_departure_time: '07:35',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '2 j ',
    flight_number: 'QG-682',
    full_via: 'CGK-DPS(07:35-10:35)',
    name: 'Citilink',
    price_adult: 1216000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      '14eb18dd2681bc70c00969fc89424b7d575d59c7933441eddc5b39dfffcebaab',
    stop: 'Langsung',
  },
  {
    arrival_date: '2020-01-16 14:40:00',
    arrival_time: '14:40',
    departure_date: '2020-01-16 11:40:00',
    departure_time: '11:40',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 14:40',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 11:40',
        duration_hour: '2',
        duration_minute: '0',
        duration_time: 120,
        flight_number: 'QG-684',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '14:40',
        simple_departure_time: '11:40',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '2 j ',
    flight_number: 'QG-684',
    full_via: 'CGK-DPS(11:40-14:40)',
    name: 'Citilink',
    price_adult: 1216000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      '3736a222eec10fb88e740b4119e35c990e1d520949cc67368deb407808801c10',
    stop: 'Langsung',
  },
  {
    arrival_date: '2020-01-16 16:20:00',
    arrival_time: '16:20',
    departure_date: '2020-01-16 13:20:00',
    departure_time: '13:20',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 16:20',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 13:20',
        duration_hour: '2',
        duration_minute: '0',
        duration_time: 120,
        flight_number: 'QG-686',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '16:20',
        simple_departure_time: '13:20',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '2 j ',
    flight_number: 'QG-686',
    full_via: 'CGK-DPS(13:20-16:20)',
    name: 'Citilink',
    price_adult: 1216000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      'cc542cd07bb6871cabfa0b464a430d45ec891ff90a9f76d41697e357d3b5b35a',
    stop: 'Langsung',
  },
  {
    arrival_date: '2020-01-16 19:40:00',
    arrival_time: '19:40',
    departure_date: '2020-01-16 16:40:00',
    departure_time: '16:40',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 19:40',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 16:40',
        duration_hour: '2',
        duration_minute: '0',
        duration_time: 120,
        flight_number: 'QG-688',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '19:40',
        simple_departure_time: '16:40',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '2 j ',
    flight_number: 'QG-688',
    full_via: 'CGK-DPS(16:40-19:40)',
    name: 'Citilink',
    price_adult: 1033000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      '3150e3a2597202c4fb1ea3a310e3b40607a9907449e1395911b68ac9281e94fd',
    stop: 'Langsung',
  },
  {
    arrival_date: '2020-01-16 09:45:00',
    arrival_time: '09:45',
    departure_date: '2020-01-16 04:10:00',
    departure_time: '04:10',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: 'Juanda',
        arrival_city: 'SUB',
        arrival_city_name: 'Surabaya',
        arrival_date_time: '2020-01-16 05:40',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 04:10',
        duration_hour: '1',
        duration_minute: '30',
        duration_time: 90,
        flight_number: 'QG-710',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '05:40',
        simple_departure_time: '04:10',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: 'Surabaya',
        transit_arrival_text_time: '2020-01-16 05:40',
        transit_duration_hour: 2,
        transit_duration_minute: 15,
      },
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 09:45',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Juanda',
        departure_city: 'SUB',
        departure_city_name: 'Surabaya',
        departure_date_time: '2020-01-16 07:55',
        duration_hour: '0',
        duration_minute: '50',
        duration_time: 50,
        flight_number: 'QG-694',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '09:45',
        simple_departure_time: '07:55',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '4 j 35 m',
    flight_number: 'QG-710',
    full_via: 'CGK-SUB(04:10-05:40) SUB-DPS(07:55-09:45)',
    name: 'Citilink',
    price_adult: 1216000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      '1bba9270db79a10270816a96d0fea517c2d13afa81788b348b1a7af9118703b8',
    stop: '1 transit',
  },
  {
    arrival_date: '2020-01-16 14:00:00',
    arrival_time: '14:00',
    departure_date: '2020-01-16 07:45:00',
    departure_time: '07:45',
    detail: [
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: 'Juanda',
        arrival_city: 'SUB',
        arrival_city_name: 'Surabaya',
        arrival_date_time: '2020-01-16 09:15',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Soekarno Hatta Intl Airport',
        departure_city: 'CGK',
        departure_city_name: 'Jakarta',
        departure_date_time: '2020-01-16 07:45',
        duration_hour: '1',
        duration_minute: '30',
        duration_time: 90,
        flight_number: 'QG-714',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '09:15',
        simple_departure_time: '07:45',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: 'Surabaya',
        transit_arrival_text_time: '2020-01-16 09:15',
        transit_duration_hour: 2,
        transit_duration_minute: 20,
      },
      {
        airlines_name: 'CITILINK',
        airlines_short_real_name: 'CITILINK',
        airlines_short_real_name_ucwords: 'Citilink',
        airport_tax: false,
        arrival_airport_name: "Ngurah Rai Int'l",
        arrival_city: 'DPS',
        arrival_city_name: 'Bali /Denpasar',
        arrival_date_time: '2020-01-16 14:00',
        check_in_baggage: 0,
        check_in_baggage_unit: '',
        class: '',
        class_w: '',
        departure_airport_name: 'Juanda',
        departure_city: 'SUB',
        departure_city_name: 'Surabaya',
        departure_date_time: '2020-01-16 11:35',
        duration_hour: '1',
        duration_minute: '25',
        duration_time: 85,
        flight_number: 'QG-668',
        has_food: '',
        img_src:
          'https://tvlk.imgix.net/imageResource/2015/12/17/1450350561012-6584b693edd67d75cfc25ecff41c5704.png',
        operated_by: 'Citilink',
        service_class: '',
        simple_arrival_time: '14:00',
        simple_departure_time: '11:35',
        string_arrival_date: '',
        string_arrival_date_short: '',
        string_departure_date: '',
        string_departure_date_short: '',
        terminal: 'Domestic',
        transit_arrival_text_city: '',
        transit_arrival_text_time: '',
        transit_duration_hour: 0,
        transit_duration_minute: 0,
      },
    ],
    duration: '5 j 15 m',
    flight_number: 'QG-714',
    full_via: 'CGK-SUB(07:45-09:15) SUB-DPS(11:35-14:00)',
    name: 'Citilink',
    price_adult: 1216000,
    price_child: 0,
    price_infant: 0,
    schedule_id:
      'd823ab049fb6e86c449bd2ab8c8b67c177044a2c4fa0dc6c3dd53db7d61e07a6',
    stop: '1 transit',
  },
];

export {date, dataFlight};
