const dataCountry = [
  {
    id: 1,
    nicename: 'Afghanistan',
    iso: 'AF',
    phonecode: 93,
  },
  {
    id: 243,
    nicename: 'Aland Islands',
    iso: 'AX',
    phonecode: 358,
  },
  {
    id: 2,
    nicename: 'Albania',
    iso: 'AL',
    phonecode: 355,
  },
  {
    id: 3,
    nicename: 'Algeria',
    iso: 'DZ',
    phonecode: 213,
  },
  {
    id: 4,
    nicename: 'American Samoa',
    iso: 'AS',
    phonecode: 1684,
  },
  {
    id: 5,
    nicename: 'Andorra',
    iso: 'AD',
    phonecode: 376,
  },
  {
    id: 6,
    nicename: 'Angola',
    iso: 'AO',
    phonecode: 244,
  },
  {
    id: 7,
    nicename: 'Anguilla',
    iso: 'AI',
    phonecode: 1264,
  },
  {
    id: 8,
    nicename: 'Antarctica',
    iso: 'AQ',
    phonecode: 0,
  },
  {
    id: 9,
    nicename: 'Antigua and Barbuda',
    iso: 'AG',
    phonecode: 1268,
  },
  {
    id: 10,
    nicename: 'Argentina',
    iso: 'AR',
    phonecode: 54,
  },
  {
    id: 11,
    nicename: 'Armenia',
    iso: 'AM',
    phonecode: 374,
  },
  {
    id: 12,
    nicename: 'Aruba',
    iso: 'AW',
    phonecode: 297,
  },
  {
    id: 241,
    nicename: 'Asia / Pacific Region',
    iso: 'AP',
    phonecode: 0,
  },
  {
    id: 13,
    nicename: 'Australia',
    iso: 'AU',
    phonecode: 61,
  },
  {
    id: 14,
    nicename: 'Austria',
    iso: 'AT',
    phonecode: 43,
  },
  {
    id: 15,
    nicename: 'Azerbaijan',
    iso: 'AZ',
    phonecode: 994,
  },
  {
    id: 16,
    nicename: 'Bahamas',
    iso: 'BS',
    phonecode: 1242,
  },
  {
    id: 17,
    nicename: 'Bahrain',
    iso: 'BH',
    phonecode: 973,
  },
  {
    id: 18,
    nicename: 'Bangladesh',
    iso: 'BD',
    phonecode: 880,
  },
  {
    id: 19,
    nicename: 'Barbados',
    iso: 'BB',
    phonecode: 1246,
  },
  {
    id: 20,
    nicename: 'Belarus',
    iso: 'BY',
    phonecode: 375,
  },
  {
    id: 21,
    nicename: 'Belgium',
    iso: 'BE',
    phonecode: 32,
  },
  {
    id: 22,
    nicename: 'Belize',
    iso: 'BZ',
    phonecode: 501,
  },
  {
    id: 23,
    nicename: 'Benin',
    iso: 'BJ',
    phonecode: 229,
  },
  {
    id: 24,
    nicename: 'Bermuda',
    iso: 'BM',
    phonecode: 1441,
  },
  {
    id: 25,
    nicename: 'Bhutan',
    iso: 'BT',
    phonecode: 975,
  },
  {
    id: 26,
    nicename: 'Bolivia',
    iso: 'BO',
    phonecode: 591,
  },
  {
    id: 244,
    nicename: 'Bonaire, Sint Eustatius and Saba',
    iso: 'BQ',
    phonecode: 599,
  },
  {
    id: 27,
    nicename: 'Bosnia and Herzegovina',
    iso: 'BA',
    phonecode: 387,
  },
  {
    id: 28,
    nicename: 'Botswana',
    iso: 'BW',
    phonecode: 267,
  },
  {
    id: 29,
    nicename: 'Bouvet Island',
    iso: 'BV',
    phonecode: 0,
  },
  {
    id: 30,
    nicename: 'Brazil',
    iso: 'BR',
    phonecode: 55,
  },
  {
    id: 31,
    nicename: 'British Indian Ocean Territory',
    iso: 'IO',
    phonecode: 246,
  },
  {
    id: 32,
    nicename: 'Brunei Darussalam',
    iso: 'BN',
    phonecode: 673,
  },
  {
    id: 33,
    nicename: 'Bulgaria',
    iso: 'BG',
    phonecode: 359,
  },
  {
    id: 34,
    nicename: 'Burkina Faso',
    iso: 'BF',
    phonecode: 226,
  },
  {
    id: 35,
    nicename: 'Burundi',
    iso: 'BI',
    phonecode: 257,
  },
  {
    id: 36,
    nicename: 'Cambodia',
    iso: 'KH',
    phonecode: 855,
  },
  {
    id: 37,
    nicename: 'Cameroon',
    iso: 'CM',
    phonecode: 237,
  },
  {
    id: 38,
    nicename: 'Canada',
    iso: 'CA',
    phonecode: 1,
  },
  {
    id: 39,
    nicename: 'Cape Verde',
    iso: 'CV',
    phonecode: 238,
  },
  {
    id: 40,
    nicename: 'Cayman Islands',
    iso: 'KY',
    phonecode: 1345,
  },
  {
    id: 41,
    nicename: 'Central African Republic',
    iso: 'CF',
    phonecode: 236,
  },
  {
    id: 42,
    nicename: 'Chad',
    iso: 'TD',
    phonecode: 235,
  },
  {
    id: 43,
    nicename: 'Chile',
    iso: 'CL',
    phonecode: 56,
  },
  {
    id: 44,
    nicename: 'China',
    iso: 'CN',
    phonecode: 86,
  },
  {
    id: 45,
    nicename: 'Christmas Island',
    iso: 'CX',
    phonecode: 61,
  },
  {
    id: 46,
    nicename: 'Cocos (Keeling) Islands',
    iso: 'CC',
    phonecode: 672,
  },
  {
    id: 47,
    nicename: 'Colombia',
    iso: 'CO',
    phonecode: 57,
  },
  {
    id: 48,
    nicename: 'Comoros',
    iso: 'KM',
    phonecode: 269,
  },
  {
    id: 49,
    nicename: 'Congo',
    iso: 'CG',
    phonecode: 242,
  },
  {
    id: 50,
    nicename: 'Congo, the Democratic Republic of the',
    iso: 'CD',
    phonecode: 242,
  },
  {
    id: 51,
    nicename: 'Cook Islands',
    iso: 'CK',
    phonecode: 682,
  },
  {
    id: 52,
    nicename: 'Costa Rica',
    iso: 'CR',
    phonecode: 506,
  },
  {
    id: 53,
    nicename: "Cote D'Ivoire",
    iso: 'CI',
    phonecode: 225,
  },
  {
    id: 54,
    nicename: 'Croatia',
    iso: 'HR',
    phonecode: 385,
  },
  {
    id: 55,
    nicename: 'Cuba',
    iso: 'CU',
    phonecode: 53,
  },
  {
    id: 245,
    nicename: 'Curacao',
    iso: 'CW',
    phonecode: 599,
  },
  {
    id: 56,
    nicename: 'Cyprus',
    iso: 'CY',
    phonecode: 357,
  },
  {
    id: 57,
    nicename: 'Czech Republic',
    iso: 'CZ',
    phonecode: 420,
  },
  {
    id: 58,
    nicename: 'Denmark',
    iso: 'DK',
    phonecode: 45,
  },
  {
    id: 59,
    nicename: 'Djibouti',
    iso: 'DJ',
    phonecode: 253,
  },
  {
    id: 60,
    nicename: 'Dominica',
    iso: 'DM',
    phonecode: 1767,
  },
  {
    id: 61,
    nicename: 'Dominican Republic',
    iso: 'DO',
    phonecode: 1809,
  },
  {
    id: 62,
    nicename: 'Ecuador',
    iso: 'EC',
    phonecode: 593,
  },
  {
    id: 63,
    nicename: 'Egypt',
    iso: 'EG',
    phonecode: 20,
  },
  {
    id: 64,
    nicename: 'El Salvador',
    iso: 'SV',
    phonecode: 503,
  },
  {
    id: 65,
    nicename: 'Equatorial Guinea',
    iso: 'GQ',
    phonecode: 240,
  },
  {
    id: 66,
    nicename: 'Eritrea',
    iso: 'ER',
    phonecode: 291,
  },
  {
    id: 67,
    nicename: 'Estonia',
    iso: 'EE',
    phonecode: 372,
  },
  {
    id: 68,
    nicename: 'Ethiopia',
    iso: 'ET',
    phonecode: 251,
  },
  {
    id: 69,
    nicename: 'Falkland Islands (Malvinas)',
    iso: 'FK',
    phonecode: 500,
  },
  {
    id: 70,
    nicename: 'Faroe Islands',
    iso: 'FO',
    phonecode: 298,
  },
  {
    id: 71,
    nicename: 'Fiji',
    iso: 'FJ',
    phonecode: 679,
  },
  {
    id: 72,
    nicename: 'Finland',
    iso: 'FI',
    phonecode: 358,
  },
  {
    id: 73,
    nicename: 'France',
    iso: 'FR',
    phonecode: 33,
  },
  {
    id: 74,
    nicename: 'French Guiana',
    iso: 'GF',
    phonecode: 594,
  },
  {
    id: 75,
    nicename: 'French Polynesia',
    iso: 'PF',
    phonecode: 689,
  },
  {
    id: 76,
    nicename: 'French Southern Territories',
    iso: 'TF',
    phonecode: 0,
  },
  {
    id: 77,
    nicename: 'Gabon',
    iso: 'GA',
    phonecode: 241,
  },
  {
    id: 78,
    nicename: 'Gambia',
    iso: 'GM',
    phonecode: 220,
  },
  {
    id: 79,
    nicename: 'Georgia',
    iso: 'GE',
    phonecode: 995,
  },
  {
    id: 80,
    nicename: 'Germany',
    iso: 'DE',
    phonecode: 49,
  },
  {
    id: 81,
    nicename: 'Ghana',
    iso: 'GH',
    phonecode: 233,
  },
  {
    id: 82,
    nicename: 'Gibraltar',
    iso: 'GI',
    phonecode: 350,
  },
  {
    id: 83,
    nicename: 'Greece',
    iso: 'GR',
    phonecode: 30,
  },
  {
    id: 84,
    nicename: 'Greenland',
    iso: 'GL',
    phonecode: 299,
  },
  {
    id: 85,
    nicename: 'Grenada',
    iso: 'GD',
    phonecode: 1473,
  },
  {
    id: 86,
    nicename: 'Guadeloupe',
    iso: 'GP',
    phonecode: 590,
  },
  {
    id: 87,
    nicename: 'Guam',
    iso: 'GU',
    phonecode: 1671,
  },
  {
    id: 88,
    nicename: 'Guatemala',
    iso: 'GT',
    phonecode: 502,
  },
  {
    id: 246,
    nicename: 'Guernsey',
    iso: 'GG',
    phonecode: 44,
  },
  {
    id: 89,
    nicename: 'Guinea',
    iso: 'GN',
    phonecode: 224,
  },
  {
    id: 90,
    nicename: 'Guinea-Bissau',
    iso: 'GW',
    phonecode: 245,
  },
  {
    id: 91,
    nicename: 'Guyana',
    iso: 'GY',
    phonecode: 592,
  },
  {
    id: 92,
    nicename: 'Haiti',
    iso: 'HT',
    phonecode: 509,
  },
  {
    id: 93,
    nicename: 'Heard Island and Mcdonald Islands',
    iso: 'HM',
    phonecode: 0,
  },
  {
    id: 94,
    nicename: 'Holy See (Vatican City State)',
    iso: 'VA',
    phonecode: 39,
  },
  {
    id: 95,
    nicename: 'Honduras',
    iso: 'HN',
    phonecode: 504,
  },
  {
    id: 96,
    nicename: 'Hong Kong',
    iso: 'HK',
    phonecode: 852,
  },
  {
    id: 97,
    nicename: 'Hungary',
    iso: 'HU',
    phonecode: 36,
  },
  {
    id: 98,
    nicename: 'Iceland',
    iso: 'IS',
    phonecode: 354,
  },
  {
    id: 99,
    nicename: 'India',
    iso: 'IN',
    phonecode: 91,
  },
  {
    id: 100,
    nicename: 'Indonesia',
    iso: 'ID',
    phonecode: 62,
  },
  {
    id: 101,
    nicename: 'Iran, Islamic Republic of',
    iso: 'IR',
    phonecode: 98,
  },
  {
    id: 102,
    nicename: 'Iraq',
    iso: 'IQ',
    phonecode: 964,
  },
  {
    id: 103,
    nicename: 'Ireland',
    iso: 'IE',
    phonecode: 353,
  },
  {
    id: 247,
    nicename: 'Isle of Man',
    iso: 'IM',
    phonecode: 44,
  },
  {
    id: 104,
    nicename: 'Israel',
    iso: 'IL',
    phonecode: 972,
  },
  {
    id: 105,
    nicename: 'Italy',
    iso: 'IT',
    phonecode: 39,
  },
  {
    id: 106,
    nicename: 'Jamaica',
    iso: 'JM',
    phonecode: 1876,
  },
  {
    id: 107,
    nicename: 'Japan',
    iso: 'JP',
    phonecode: 81,
  },
  {
    id: 248,
    nicename: 'Jersey',
    iso: 'JE',
    phonecode: 44,
  },
  {
    id: 108,
    nicename: 'Jordan',
    iso: 'JO',
    phonecode: 962,
  },
  {
    id: 109,
    nicename: 'Kazakhstan',
    iso: 'KZ',
    phonecode: 7,
  },
  {
    id: 110,
    nicename: 'Kenya',
    iso: 'KE',
    phonecode: 254,
  },
  {
    id: 111,
    nicename: 'Kiribati',
    iso: 'KI',
    phonecode: 686,
  },
  {
    id: 112,
    nicename: "Korea, Democratic People's Republic of",
    iso: 'KP',
    phonecode: 850,
  },
  {
    id: 113,
    nicename: 'Korea, Republic of',
    iso: 'KR',
    phonecode: 82,
  },
  {
    id: 249,
    nicename: 'Kosovo',
    iso: 'XK',
    phonecode: 381,
  },
  {
    id: 114,
    nicename: 'Kuwait',
    iso: 'KW',
    phonecode: 965,
  },
  {
    id: 115,
    nicename: 'Kyrgyzstan',
    iso: 'KG',
    phonecode: 996,
  },
  {
    id: 116,
    nicename: "Lao People's Democratic Republic",
    iso: 'LA',
    phonecode: 856,
  },
  {
    id: 117,
    nicename: 'Latvia',
    iso: 'LV',
    phonecode: 371,
  },
  {
    id: 118,
    nicename: 'Lebanon',
    iso: 'LB',
    phonecode: 961,
  },
  {
    id: 119,
    nicename: 'Lesotho',
    iso: 'LS',
    phonecode: 266,
  },
  {
    id: 120,
    nicename: 'Liberia',
    iso: 'LR',
    phonecode: 231,
  },
  {
    id: 121,
    nicename: 'Libyan Arab Jamahiriya',
    iso: 'LY',
    phonecode: 218,
  },
  {
    id: 122,
    nicename: 'Liechtenstein',
    iso: 'LI',
    phonecode: 423,
  },
  {
    id: 123,
    nicename: 'Lithuania',
    iso: 'LT',
    phonecode: 370,
  },
  {
    id: 124,
    nicename: 'Luxembourg',
    iso: 'LU',
    phonecode: 352,
  },
  {
    id: 125,
    nicename: 'Macao',
    iso: 'MO',
    phonecode: 853,
  },
  {
    id: 126,
    nicename: 'Macedonia, the Former Yugoslav Republic of',
    iso: 'MK',
    phonecode: 389,
  },
  {
    id: 127,
    nicename: 'Madagascar',
    iso: 'MG',
    phonecode: 261,
  },
  {
    id: 128,
    nicename: 'Malawi',
    iso: 'MW',
    phonecode: 265,
  },
  {
    id: 129,
    nicename: 'Malaysia',
    iso: 'MY',
    phonecode: 60,
  },
  {
    id: 130,
    nicename: 'Maldives',
    iso: 'MV',
    phonecode: 960,
  },
  {
    id: 131,
    nicename: 'Mali',
    iso: 'ML',
    phonecode: 223,
  },
  {
    id: 132,
    nicename: 'Malta',
    iso: 'MT',
    phonecode: 356,
  },
  {
    id: 133,
    nicename: 'Marshall Islands',
    iso: 'MH',
    phonecode: 692,
  },
  {
    id: 134,
    nicename: 'Martinique',
    iso: 'MQ',
    phonecode: 596,
  },
  {
    id: 135,
    nicename: 'Mauritania',
    iso: 'MR',
    phonecode: 222,
  },
  {
    id: 136,
    nicename: 'Mauritius',
    iso: 'MU',
    phonecode: 230,
  },
  {
    id: 137,
    nicename: 'Mayotte',
    iso: 'YT',
    phonecode: 269,
  },
  {
    id: 138,
    nicename: 'Mexico',
    iso: 'MX',
    phonecode: 52,
  },
  {
    id: 139,
    nicename: 'Micronesia, Federated States of',
    iso: 'FM',
    phonecode: 691,
  },
  {
    id: 140,
    nicename: 'Moldova, Republic of',
    iso: 'MD',
    phonecode: 373,
  },
  {
    id: 141,
    nicename: 'Monaco',
    iso: 'MC',
    phonecode: 377,
  },
  {
    id: 142,
    nicename: 'Mongolia',
    iso: 'MN',
    phonecode: 976,
  },
  {
    id: 242,
    nicename: 'Montenegro',
    iso: 'ME',
    phonecode: 382,
  },
  {
    id: 143,
    nicename: 'Montserrat',
    iso: 'MS',
    phonecode: 1664,
  },
  {
    id: 144,
    nicename: 'Morocco',
    iso: 'MA',
    phonecode: 212,
  },
  {
    id: 145,
    nicename: 'Mozambique',
    iso: 'MZ',
    phonecode: 258,
  },
  {
    id: 146,
    nicename: 'Myanmar',
    iso: 'MM',
    phonecode: 95,
  },
  {
    id: 147,
    nicename: 'Namibia',
    iso: 'NA',
    phonecode: 264,
  },
  {
    id: 148,
    nicename: 'Nauru',
    iso: 'NR',
    phonecode: 674,
  },
  {
    id: 149,
    nicename: 'Nepal',
    iso: 'NP',
    phonecode: 977,
  },
  {
    id: 150,
    nicename: 'Netherlands',
    iso: 'NL',
    phonecode: 31,
  },
  {
    id: 151,
    nicename: 'Netherlands Antilles',
    iso: 'AN',
    phonecode: 599,
  },
  {
    id: 152,
    nicename: 'New Caledonia',
    iso: 'NC',
    phonecode: 687,
  },
  {
    id: 153,
    nicename: 'New Zealand',
    iso: 'NZ',
    phonecode: 64,
  },
  {
    id: 154,
    nicename: 'Nicaragua',
    iso: 'NI',
    phonecode: 505,
  },
  {
    id: 155,
    nicename: 'Niger',
    iso: 'NE',
    phonecode: 227,
  },
  {
    id: 156,
    nicename: 'Nigeria',
    iso: 'NG',
    phonecode: 234,
  },
  {
    id: 157,
    nicename: 'Niue',
    iso: 'NU',
    phonecode: 683,
  },
  {
    id: 158,
    nicename: 'Norfolk Island',
    iso: 'NF',
    phonecode: 672,
  },
  {
    id: 159,
    nicename: 'Northern Mariana Islands',
    iso: 'MP',
    phonecode: 1670,
  },
  {
    id: 160,
    nicename: 'Norway',
    iso: 'NO',
    phonecode: 47,
  },
  {
    id: 161,
    nicename: 'Oman',
    iso: 'OM',
    phonecode: 968,
  },
  {
    id: 162,
    nicename: 'Pakistan',
    iso: 'PK',
    phonecode: 92,
  },
  {
    id: 163,
    nicename: 'Palau',
    iso: 'PW',
    phonecode: 680,
  },
  {
    id: 164,
    nicename: 'Palestinian Territory, Occupied',
    iso: 'PS',
    phonecode: 970,
  },
  {
    id: 165,
    nicename: 'Panama',
    iso: 'PA',
    phonecode: 507,
  },
  {
    id: 166,
    nicename: 'Papua New Guinea',
    iso: 'PG',
    phonecode: 675,
  },
  {
    id: 167,
    nicename: 'Paraguay',
    iso: 'PY',
    phonecode: 595,
  },
  {
    id: 168,
    nicename: 'Peru',
    iso: 'PE',
    phonecode: 51,
  },
  {
    id: 169,
    nicename: 'Philippines',
    iso: 'PH',
    phonecode: 63,
  },
  {
    id: 170,
    nicename: 'Pitcairn',
    iso: 'PN',
    phonecode: 0,
  },
  {
    id: 171,
    nicename: 'Poland',
    iso: 'PL',
    phonecode: 48,
  },
  {
    id: 172,
    nicename: 'Portugal',
    iso: 'PT',
    phonecode: 351,
  },
  {
    id: 173,
    nicename: 'Puerto Rico',
    iso: 'PR',
    phonecode: 1787,
  },
  {
    id: 174,
    nicename: 'Qatar',
    iso: 'QA',
    phonecode: 974,
  },
  {
    id: 175,
    nicename: 'Reunion',
    iso: 'RE',
    phonecode: 262,
  },
  {
    id: 176,
    nicename: 'Romania',
    iso: 'RO',
    phonecode: 40,
  },
  {
    id: 177,
    nicename: 'Russian Federation',
    iso: 'RU',
    phonecode: 70,
  },
  {
    id: 178,
    nicename: 'Rwanda',
    iso: 'RW',
    phonecode: 250,
  },
  {
    id: 250,
    nicename: 'Saint Barthelemy',
    iso: 'BL',
    phonecode: 590,
  },
  {
    id: 179,
    nicename: 'Saint Helena',
    iso: 'SH',
    phonecode: 290,
  },
  {
    id: 180,
    nicename: 'Saint Kitts and Nevis',
    iso: 'KN',
    phonecode: 1869,
  },
  {
    id: 181,
    nicename: 'Saint Lucia',
    iso: 'LC',
    phonecode: 1758,
  },
  {
    id: 251,
    nicename: 'Saint Martin',
    iso: 'MF',
    phonecode: 590,
  },
  {
    id: 182,
    nicename: 'Saint Pierre and Miquelon',
    iso: 'PM',
    phonecode: 508,
  },
  {
    id: 183,
    nicename: 'Saint Vincent and the Grenadines',
    iso: 'VC',
    phonecode: 1784,
  },
  {
    id: 184,
    nicename: 'Samoa',
    iso: 'WS',
    phonecode: 684,
  },
  {
    id: 185,
    nicename: 'San Marino',
    iso: 'SM',
    phonecode: 378,
  },
  {
    id: 186,
    nicename: 'Sao Tome and Principe',
    iso: 'ST',
    phonecode: 239,
  },
  {
    id: 187,
    nicename: 'Saudi Arabia',
    iso: 'SA',
    phonecode: 966,
  },
  {
    id: 188,
    nicename: 'Senegal',
    iso: 'SN',
    phonecode: 221,
  },
  {
    id: 240,
    nicename: 'Serbia',
    iso: 'RS',
    phonecode: 381,
  },
  {
    id: 189,
    nicename: 'Serbia and Montenegro',
    iso: 'CS',
    phonecode: 381,
  },
  {
    id: 190,
    nicename: 'Seychelles',
    iso: 'SC',
    phonecode: 248,
  },
  {
    id: 191,
    nicename: 'Sierra Leone',
    iso: 'SL',
    phonecode: 232,
  },
  {
    id: 192,
    nicename: 'Singapore',
    iso: 'SG',
    phonecode: 65,
  },
  {
    id: 252,
    nicename: 'Sint Maarten',
    iso: 'SX',
    phonecode: 1,
  },
  {
    id: 193,
    nicename: 'Slovakia',
    iso: 'SK',
    phonecode: 421,
  },
  {
    id: 194,
    nicename: 'Slovenia',
    iso: 'SI',
    phonecode: 386,
  },
  {
    id: 195,
    nicename: 'Solomon Islands',
    iso: 'SB',
    phonecode: 677,
  },
  {
    id: 196,
    nicename: 'Somalia',
    iso: 'SO',
    phonecode: 252,
  },
  {
    id: 197,
    nicename: 'South Africa',
    iso: 'ZA',
    phonecode: 27,
  },
  {
    id: 198,
    nicename: 'South Georgia and the South Sandwich Islands',
    iso: 'GS',
    phonecode: 0,
  },
  {
    id: 253,
    nicename: 'South Sudan',
    iso: 'SS',
    phonecode: 211,
  },
  {
    id: 199,
    nicename: 'Spain',
    iso: 'ES',
    phonecode: 34,
  },
  {
    id: 200,
    nicename: 'Sri Lanka',
    iso: 'LK',
    phonecode: 94,
  },
  {
    id: 201,
    nicename: 'Sudan',
    iso: 'SD',
    phonecode: 249,
  },
  {
    id: 202,
    nicename: 'Suriname',
    iso: 'SR',
    phonecode: 597,
  },
  {
    id: 203,
    nicename: 'Svalbard and Jan Mayen',
    iso: 'SJ',
    phonecode: 47,
  },
  {
    id: 204,
    nicename: 'Swaziland',
    iso: 'SZ',
    phonecode: 268,
  },
  {
    id: 205,
    nicename: 'Sweden',
    iso: 'SE',
    phonecode: 46,
  },
  {
    id: 206,
    nicename: 'Switzerland',
    iso: 'CH',
    phonecode: 41,
  },
  {
    id: 207,
    nicename: 'Syrian Arab Republic',
    iso: 'SY',
    phonecode: 963,
  },
  {
    id: 208,
    nicename: 'Taiwan, Province of China',
    iso: 'TW',
    phonecode: 886,
  },
  {
    id: 209,
    nicename: 'Tajikistan',
    iso: 'TJ',
    phonecode: 992,
  },
  {
    id: 210,
    nicename: 'Tanzania, United Republic of',
    iso: 'TZ',
    phonecode: 255,
  },
  {
    id: 211,
    nicename: 'Thailand',
    iso: 'TH',
    phonecode: 66,
  },
  {
    id: 212,
    nicename: 'Timor-Leste',
    iso: 'TL',
    phonecode: 670,
  },
  {
    id: 213,
    nicename: 'Togo',
    iso: 'TG',
    phonecode: 228,
  },
  {
    id: 214,
    nicename: 'Tokelau',
    iso: 'TK',
    phonecode: 690,
  },
  {
    id: 215,
    nicename: 'Tonga',
    iso: 'TO',
    phonecode: 676,
  },
  {
    id: 216,
    nicename: 'Trinidad and Tobago',
    iso: 'TT',
    phonecode: 1868,
  },
  {
    id: 217,
    nicename: 'Tunisia',
    iso: 'TN',
    phonecode: 216,
  },
  {
    id: 218,
    nicename: 'Turkey',
    iso: 'TR',
    phonecode: 90,
  },
  {
    id: 219,
    nicename: 'Turkmenistan',
    iso: 'TM',
    phonecode: 7370,
  },
  {
    id: 220,
    nicename: 'Turks and Caicos Islands',
    iso: 'TC',
    phonecode: 1649,
  },
  {
    id: 221,
    nicename: 'Tuvalu',
    iso: 'TV',
    phonecode: 688,
  },
  {
    id: 222,
    nicename: 'Uganda',
    iso: 'UG',
    phonecode: 256,
  },
  {
    id: 223,
    nicename: 'Ukraine',
    iso: 'UA',
    phonecode: 380,
  },
  {
    id: 224,
    nicename: 'United Arab Emirates',
    iso: 'AE',
    phonecode: 971,
  },
  {
    id: 225,
    nicename: 'United Kingdom',
    iso: 'GB',
    phonecode: 44,
  },
  {
    id: 226,
    nicename: 'United States',
    iso: 'US',
    phonecode: 1,
  },
  {
    id: 227,
    nicename: 'United States Minor Outlying Islands',
    iso: 'UM',
    phonecode: 1,
  },
  {
    id: 228,
    nicename: 'Uruguay',
    iso: 'UY',
    phonecode: 598,
  },
  {
    id: 229,
    nicename: 'Uzbekistan',
    iso: 'UZ',
    phonecode: 998,
  },
  {
    id: 230,
    nicename: 'Vanuatu',
    iso: 'VU',
    phonecode: 678,
  },
  {
    id: 231,
    nicename: 'Venezuela',
    iso: 'VE',
    phonecode: 58,
  },
  {
    id: 232,
    nicename: 'Viet Nam',
    iso: 'VN',
    phonecode: 84,
  },
  {
    id: 233,
    nicename: 'Virgin Islands, British',
    iso: 'VG',
    phonecode: 1284,
  },
  {
    id: 234,
    nicename: 'Virgin Islands, U.s.',
    iso: 'VI',
    phonecode: 1340,
  },
  {
    id: 235,
    nicename: 'Wallis and Futuna',
    iso: 'WF',
    phonecode: 681,
  },
  {
    id: 236,
    nicename: 'Western Sahara',
    iso: 'EH',
    phonecode: 212,
  },
  {
    id: 237,
    nicename: 'Yemen',
    iso: 'YE',
    phonecode: 967,
  },
  {
    id: 238,
    nicename: 'Zambia',
    iso: 'ZM',
    phonecode: 260,
  },
  {
    id: 239,
    nicename: 'Zimbabwe',
    iso: 'ZW',
    phonecode: 263,
  },
];

export default dataCountry;
